apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-example-deployment
  namespace: hpa-example-namespace
  labels:
    app: hpa-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-example
  template:
    metadata:
      labels:
        app: hpa-example
    spec:
      containers:
      - name: php-container
        image: n1c0l4stournier/hpa.example:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "100m"