apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-custom-deployment
  namespace: hpa-custom-namespace
  labels:
    app: hpa-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa-custom
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: hpa-custom
    spec:
      containers:
      - name: hpa-custom
        image: luxas/autoscale-demo:v0.1.2
        ports:
        - containerPort: 8080