kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: hpa-custom-horizontalpodautoscaler
  namespace: hpa-custom-namespace

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-custom-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: http_requests_total
      targetAverageValue: 7000