apiVersion: v1
kind: Service
metadata:
  name: hpa-custom-service
  namespace: hpa-custom-namespace
spec:
  type: NodePort
  selector:
    app: hpa-custom
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080