apiVersion: v1
kind: Service
metadata:
  name: hpa-example-service
  namespace: hpa-example-namespace
spec:
  selector:
    app: hpa-example
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80